security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: null }
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            guard:
                authenticators:
                    - App\Domain\Service\Security\LoginFormAuthenticator
            logout:
                path: logout
                target: home
                
        #secured_area:
        #    form_login:
        #        login_path: login
        #        check_path: login_check
        #        csrf_token_generator: security.csrf.token_manager

    encoders:
        App\Domain\Entity\User:   
            algorithm: bcrypt
        
    access_control:
        #- { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, roles: ROLE_ADMIN }

        # - { path: ^/profile, roles: ROLE_USER }
